spring:
  data:
    redis:
      host: www.velvetshiki.cn
      port: 6379
      password: 123456
      lettuce:
        # 配置redis连接池，分别为最大用户连接数，最大空闲连接数，最小空闲连接数，最大连接等待时间
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 100ms