profile:
  server:
    port: 7778

  mysql:
    host: localhost
    name: root
    password: 123456
    database: cloud_model

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 2

  redisson:
    address: 127.0.0.1
    port: 6379
    password: 123456
