# springboot基本配置
spring:
  # 项目基本
  application:
    name: BlogSystem_v1

  # 数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.94.180.58:3306/blogDB?rewriteBatchedStatements=true&characterEncoding=UTF-8&useUnicode=true&characterSetResults=UTF-8
    username: root
    password: zcx984288627

  # 文件上传，代理服务器nginx也需要配置client_max_body_size 10m;
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 10MB

# tomcat服务器配置
server:
  port: 8000
#  address: localhost   不配置即0.0.0.0，允许任何主机访问

# aliyun OSS配置

# mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# mybatis-plus
mybatis-plus:
  type-aliases-package: com.vs.pojo
  mapper-locations: "classpath*:/mapper/**/*.xml"
  global-config:
    db-config:
      id-type: auto     # 主键自增长
#      logic-delete-field: deleted   # 逻辑删除相关
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler

# 图片存储路径和输出路径
files:
  avatar:
#    storePath: C:\Users\Shiki\Desktop\avatar\
    storePath: /home/shiki/rsc/static/images/
    accessPath: http://www.velvetshiki.cn/images/

# 日志输出路径(或选择logback-spring.xml使用)
logging:
  file:
#    name: /home/shiki/projects/user_manager_system/back_end/logs/spring-boot.log
#    path: /home/shiki/projects/user_manager_system/back_end/logs
    name: D:\Code\java-repo\BlogSystem_v1\src\main\resources\logs\spring-boot.log
    path: D:\Code\java-repo\BlogSystem_v1\src\main\resources\logs\
  level:
    # root为项目级别日志记录，包及子包若未指定将会继承自root
    # 级别分为TRACE, DEBUG, INFO, WARN, ERROR, FATAL
    root: INFO
    com.vs: DEBUG


# properties配置
# spring.application.name=BlogSystem_v1
#
## 数据库连接配置
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://1.94.180.58:3306/blogDB
#spring.datasource.username=root
#spring.datasource.password=zcx984288627
#
## 数据库对象驼峰命名
#mybatis.configuration.map-underscore-to-camel-case=true
#
## mybatis sql操作日志
#mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
#
## 文件上传配置
## 单个文件上传限制
#spring.servlet.multipart.max-file-size=10MB
## 多个文件上传限制
#spring.servlet.multipart.max-request-size=100MB