spring:
  application:
    name: customer
  rabbitmq:
    # ????rabbitMQ?ip port, ????????????????name pass????
    host: localhost
    port: 5672
    virtual-host: /cloud
    username: shiki
    password: 123456
    listener:
      simple:
        # ???????????????????????????
        prefetch: 1