# Tomcat配置
server:
  port: ${profile.server.port}
  address: 0.0.0.0

# 共享配置设置
cloud:
  redis:
    host: ${profile.redis.host}
    port: ${profile.redis.port}
    password: ${profile.redis.password}
    database: ${profile.redis.database}