profile:
  server:
    port: 7777

  mysql:
    host: localhost
    name: root
    password: 123456
    database: cloud_user

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 1

  redisson:
    address: 127.0.0.1
    port: 6379
    password: 123456
