cloud:
  server:
    port: 7777

  mysql:
    host: localhost
    username: root
    password: 123456
    database: cloud_user

  redis:
    host: localhost
    password: 123456

  redisson:
    address: 127.0.0.1:6379
    password: 123456
    connectionPoolSize: 10           #  最大连接数
    connectionMinimumIdleSize: 10    # 最小空闲连接数，必须小于或等于 connectionPoolSize