# Tomcat配置
server:
  port: ${profile.server.port}
  address: 0.0.0.0
  tomcat:
    threads:
      # 并发线程数
      max: 50
    # 允许排队线程数
    accept-count: 50
    # 允许最大连接数
    max-connections: 100

# 共享配置设置
cloud:
  mysql:
    host: ${profile.mysql.host}
    name: ${profile.mysql.name}
    password: ${profile.mysql.password}
    database: ${profile.mysql.database}

  redis:
    host: ${profile.redis.host}
    port: ${profile.redis.port}
    password: ${profile.redis.password}
    database: ${profile.redis.database}

  redisson:
    address: ${profile.redisson.address}
    port: ${profile.redisson.port}
    password: ${profile.redisson.password}