gms:
  server:
    port: 8888

  mysql:
    host: www.velvetshiki.cn
    username: root
    password: zcx984288627


  redis:
    host: www.velvetshiki.cn
    password: 123456

  redisson:
    address: 1.94.180.58:6379
    password: 123456
    connectionPoolSize: 10           #  最大连接数
    connectionMinimumIdleSize: 10    # 最小空闲连接数，必须小于或等于 connectionPoolSize